name: Update Algorithm Performance Plot

on:
  push:
    branches:
      - main

jobs:
  update-plot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib # Add other dependencies as needed

    - name: Run script to update plot
      run: |
        # Your script to update the plot
        # Ensure this script actually makes changes to the repository
        python analyze_commits.py

    - name: Check for changes before commit
      run: git status

    - name: Commit and push changes
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git status # Check status after adding changes
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Update algorithm performance plot"
        git push https://github-actions:${{ secrets.ACTIONS_PAT }}@github.com/stefanpricopie/LeetCode.git HEAD:main